NUM_REPORTS = 300

ELASTIC_CLOUD_ID = "cluster:jlahdslkjfahlsdkjfhadflkjh=="
ELASTIC_USER = "elastic"
ELASTIC_PASSWORD = "lahjsdfkjlhasdf"
ELASTIC_INDEX = "intel-reports"

AZURE_OPENAI_API_KEY = "asdfasdfadsf"
AZURE_API_VERSION = "2024-02-01"
AZURE_ENDPOINT = "https://my-endpoint.openai.azure.com"
AZURE_DEPLOYMENT = "my-deployment"
AZURE_MODEL = "gpt-4o"

LOCAL_LLM_URL = "http://1.2.3.4:11434/v1"
LOCAL_LLM_API_KEY = "ollama"
LOCAL_LLM_MODEL = "mixtral"